name: service-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Use Azure Login Service Connection
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'  # Reference the Service Connection secret

      # Display available subscriptions (for debugging purposes)
      - name: List Subscriptions
        run: az account list

      # other parts of your YAML file remain unchanged

      # Deploy Bicep file
      - name: Deploy Service Connection
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 7b44425c-979b-476a-9cca-cd73b2fcff42
          resourceGroupName: my-test-dev
          template: ./serviconnection.bicep
         

